#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TaskyAndroid.Resource", IsApplication=true)]

namespace TaskyAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int AddButton = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int CancelDeleteButton = 2130837505;
			
			// aapt resource value: 0x7F020009
			public const int chkDone = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int lstItemTask = 2130837514;
			
			// aapt resource value: 0x7F020002
			public const int NameLabel = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int NameText = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int NotesLabel = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int NotesText = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int SaveButton = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int TaskDetailsHeader = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int TaskList = 2130837512;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int HomeScreen = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int TaskDetails = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int TaskListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050000
			public const int GreenActionBar = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Theme_Tasky = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int WhiteTitleText = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
